%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'multisector';
M_.dynare_version = '4.6.4';
oo_.dynare_version = '4.6.4';
options_.dynare_version = '4.6.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('multisector.log');
M_.exo_names = cell(1,1);
M_.exo_names_tex = cell(1,1);
M_.exo_names_long = cell(1,1);
M_.exo_names(1) = {'eps'};
M_.exo_names_tex(1) = {'eps'};
M_.exo_names_long(1) = {'eps'};
M_.endo_names = cell(33,1);
M_.endo_names_tex = cell(33,1);
M_.endo_names_long = cell(33,1);
M_.endo_names(1) = {'n'};
M_.endo_names_tex(1) = {'n'};
M_.endo_names_long(1) = {'Labor supply'};
M_.endo_names(2) = {'c'};
M_.endo_names_tex(2) = {'c'};
M_.endo_names_long(2) = {'Agg. consumption'};
M_.endo_names(3) = {'lambda_tau'};
M_.endo_names_tex(3) = {'lambda\_tau'};
M_.endo_names_long(3) = {'Lambda'};
M_.endo_names(4) = {'tau'};
M_.endo_names_tex(4) = {'tau'};
M_.endo_names_long(4) = {'Probability of infection'};
M_.endo_names(5) = {'I'};
M_.endo_names_tex(5) = {'I'};
M_.endo_names_long(5) = {'Infected'};
M_.endo_names(6) = {'T'};
M_.endo_names_tex(6) = {'T'};
M_.endo_names_long(6) = {'Newly infected'};
M_.endo_names(7) = {'S'};
M_.endo_names_tex(7) = {'S'};
M_.endo_names_long(7) = {'Susceptible'};
M_.endo_names(8) = {'R'};
M_.endo_names_tex(8) = {'R'};
M_.endo_names_long(8) = {'Recovered'};
M_.endo_names(9) = {'D'};
M_.endo_names_tex(9) = {'D'};
M_.endo_names_long(9) = {'Deceased'};
M_.endo_names(10) = {'C'};
M_.endo_names_tex(10) = {'C'};
M_.endo_names_long(10) = {'Agg. consumption'};
M_.endo_names(11) = {'N'};
M_.endo_names_tex(11) = {'N'};
M_.endo_names_long(11) = {'Agg. labor'};
M_.endo_names(12) = {'Ui'};
M_.endo_names_tex(12) = {'Ui'};
M_.endo_names_long(12) = {'Lifetime utility of infected'};
M_.endo_names(13) = {'Us'};
M_.endo_names_tex(13) = {'Us'};
M_.endo_names_long(13) = {'Lifetime utility of susceptible'};
M_.endo_names(14) = {'Ur'};
M_.endo_names_tex(14) = {'Ur'};
M_.endo_names_long(14) = {'Lifetime utility of recovered'};
M_.endo_names(15) = {'dD'};
M_.endo_names_tex(15) = {'dD'};
M_.endo_names_long(15) = {'Weekly death'};
M_.endo_names(16) = {'c1'};
M_.endo_names_tex(16) = {'c1'};
M_.endo_names_long(16) = {'c1'};
M_.endo_names(17) = {'c1_dev'};
M_.endo_names_tex(17) = {'c1\_dev'};
M_.endo_names_long(17) = {'c1_dev'};
M_.endo_names(18) = {'c2'};
M_.endo_names_tex(18) = {'c2'};
M_.endo_names_long(18) = {'c2'};
M_.endo_names(19) = {'c2_dev'};
M_.endo_names_tex(19) = {'c2\_dev'};
M_.endo_names_long(19) = {'c2_dev'};
M_.endo_names(20) = {'c3'};
M_.endo_names_tex(20) = {'c3'};
M_.endo_names_long(20) = {'c3'};
M_.endo_names(21) = {'c3_dev'};
M_.endo_names_tex(21) = {'c3\_dev'};
M_.endo_names_long(21) = {'c3_dev'};
M_.endo_names(22) = {'c4'};
M_.endo_names_tex(22) = {'c4'};
M_.endo_names_long(22) = {'c4'};
M_.endo_names(23) = {'c4_dev'};
M_.endo_names_tex(23) = {'c4\_dev'};
M_.endo_names_long(23) = {'c4_dev'};
M_.endo_names(24) = {'c5'};
M_.endo_names_tex(24) = {'c5'};
M_.endo_names_long(24) = {'c5'};
M_.endo_names(25) = {'c5_dev'};
M_.endo_names_tex(25) = {'c5\_dev'};
M_.endo_names_long(25) = {'c5_dev'};
M_.endo_names(26) = {'c6'};
M_.endo_names_tex(26) = {'c6'};
M_.endo_names_long(26) = {'c6'};
M_.endo_names(27) = {'c6_dev'};
M_.endo_names_tex(27) = {'c6\_dev'};
M_.endo_names_long(27) = {'c6_dev'};
M_.endo_names(28) = {'c7'};
M_.endo_names_tex(28) = {'c7'};
M_.endo_names_long(28) = {'c7'};
M_.endo_names(29) = {'c7_dev'};
M_.endo_names_tex(29) = {'c7\_dev'};
M_.endo_names_long(29) = {'c7_dev'};
M_.endo_names(30) = {'c8'};
M_.endo_names_tex(30) = {'c8'};
M_.endo_names_long(30) = {'c8'};
M_.endo_names(31) = {'c8_dev'};
M_.endo_names_tex(31) = {'c8\_dev'};
M_.endo_names_long(31) = {'c8_dev'};
M_.endo_names(32) = {'c9'};
M_.endo_names_tex(32) = {'c9'};
M_.endo_names_long(32) = {'c9'};
M_.endo_names(33) = {'c9_dev'};
M_.endo_names_tex(33) = {'c9\_dev'};
M_.endo_names_long(33) = {'c9_dev'};
M_.endo_partitions = struct();
M_.param_names = cell(26,1);
M_.param_names_tex = cell(26,1);
M_.param_names_long = cell(26,1);
M_.param_names(1) = {'pi_s'};
M_.param_names_tex(1) = {'{\pi_s}'};
M_.param_names_long(1) = {'Probability of becoming infected'};
M_.param_names(2) = {'pi_a'};
M_.param_names_tex(2) = {'{\pi_a}'};
M_.param_names_long(2) = {'Probability of autonomous infection'};
M_.param_names(3) = {'pi_r'};
M_.param_names_tex(3) = {'{\pi_r}'};
M_.param_names_long(3) = {'Probability of recovery'};
M_.param_names(4) = {'pi_d'};
M_.param_names_tex(4) = {'{\pi_d}'};
M_.param_names_long(4) = {'Probability of death'};
M_.param_names(5) = {'eta'};
M_.param_names_tex(5) = {'{\eta}'};
M_.param_names_long(5) = {'Dlasticity of substitution'};
M_.param_names(6) = {'theta'};
M_.param_names_tex(6) = {'{\theta}'};
M_.param_names_long(6) = {'Labor supply parameter'};
M_.param_names(7) = {'A'};
M_.param_names_tex(7) = {'{A}'};
M_.param_names_long(7) = {'Productivity'};
M_.param_names(8) = {'betta'};
M_.param_names_tex(8) = {'{\beta}'};
M_.param_names_long(8) = {'Discount factor'};
M_.param_names(9) = {'phi1'};
M_.param_names_tex(9) = {'{\phi_{1}}'};
M_.param_names_long(9) = {'phi1'};
M_.param_names(10) = {'ups1'};
M_.param_names_tex(10) = {'{\upsilon_{1}}'};
M_.param_names_long(10) = {'ups1'};
M_.param_names(11) = {'phi2'};
M_.param_names_tex(11) = {'{\phi_{2}}'};
M_.param_names_long(11) = {'phi2'};
M_.param_names(12) = {'ups2'};
M_.param_names_tex(12) = {'{\upsilon_{2}}'};
M_.param_names_long(12) = {'ups2'};
M_.param_names(13) = {'phi3'};
M_.param_names_tex(13) = {'{\phi_{3}}'};
M_.param_names_long(13) = {'phi3'};
M_.param_names(14) = {'ups3'};
M_.param_names_tex(14) = {'{\upsilon_{3}}'};
M_.param_names_long(14) = {'ups3'};
M_.param_names(15) = {'phi4'};
M_.param_names_tex(15) = {'{\phi_{4}}'};
M_.param_names_long(15) = {'phi4'};
M_.param_names(16) = {'ups4'};
M_.param_names_tex(16) = {'{\upsilon_{4}}'};
M_.param_names_long(16) = {'ups4'};
M_.param_names(17) = {'phi5'};
M_.param_names_tex(17) = {'{\phi_{5}}'};
M_.param_names_long(17) = {'phi5'};
M_.param_names(18) = {'ups5'};
M_.param_names_tex(18) = {'{\upsilon_{5}}'};
M_.param_names_long(18) = {'ups5'};
M_.param_names(19) = {'phi6'};
M_.param_names_tex(19) = {'{\phi_{6}}'};
M_.param_names_long(19) = {'phi6'};
M_.param_names(20) = {'ups6'};
M_.param_names_tex(20) = {'{\upsilon_{6}}'};
M_.param_names_long(20) = {'ups6'};
M_.param_names(21) = {'phi7'};
M_.param_names_tex(21) = {'{\phi_{7}}'};
M_.param_names_long(21) = {'phi7'};
M_.param_names(22) = {'ups7'};
M_.param_names_tex(22) = {'{\upsilon_{7}}'};
M_.param_names_long(22) = {'ups7'};
M_.param_names(23) = {'phi8'};
M_.param_names_tex(23) = {'{\phi_{8}}'};
M_.param_names_long(23) = {'phi8'};
M_.param_names(24) = {'ups8'};
M_.param_names_tex(24) = {'{\upsilon_{8}}'};
M_.param_names_long(24) = {'ups8'};
M_.param_names(25) = {'phi9'};
M_.param_names_tex(25) = {'{\phi_{9}}'};
M_.param_names_long(25) = {'phi9'};
M_.param_names(26) = {'ups9'};
M_.param_names_tex(26) = {'{\upsilon_{9}}'};
M_.param_names_long(26) = {'ups9'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 33;
M_.param_nbr = 26;
M_.orig_endo_nbr = 33;
M_.aux_vars = [];
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.orig_eq_nbr = 33;
M_.eq_nbr = 33;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 6 0;
 0 7 0;
 0 8 0;
 0 9 0;
 1 10 0;
 2 11 0;
 3 12 0;
 4 13 0;
 5 14 0;
 0 15 0;
 0 16 0;
 0 17 39;
 0 18 40;
 0 19 41;
 0 20 0;
 0 21 0;
 0 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;]';
M_.nstatic = 25;
M_.nfwrd   = 3;
M_.npred   = 5;
M_.nboth   = 0;
M_.nsfwrd   = 3;
M_.nspred   = 5;
M_.ndynamic   = 8;
M_.dynamic_tmp_nbr = [27; 12; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'FOC sector 1' ;
  2 , 'name' , 'c1_dev' ;
  3 , 'name' , 'FOC sector 2' ;
  4 , 'name' , 'c2_dev' ;
  5 , 'name' , 'FOC sector 3' ;
  6 , 'name' , 'c3_dev' ;
  7 , 'name' , 'FOC sector 4' ;
  8 , 'name' , 'c4_dev' ;
  9 , 'name' , 'FOC sector 5' ;
  10 , 'name' , 'c5_dev' ;
  11 , 'name' , 'FOC sector 6' ;
  12 , 'name' , 'c6_dev' ;
  13 , 'name' , 'FOC sector 7' ;
  14 , 'name' , 'c7_dev' ;
  15 , 'name' , 'FOC sector 8' ;
  16 , 'name' , 'c8_dev' ;
  17 , 'name' , 'FOC sector 9' ;
  18 , 'name' , 'c9_dev' ;
  19 , 'name' , '19' ;
  20 , 'name' , 'c' ;
  21 , 'name' , 'tau' ;
  22 , 'name' , 'lambda_tau' ;
  23 , 'name' , 'Ui' ;
  24 , 'name' , 'Ur' ;
  25 , 'name' , 'Us' ;
  26 , 'name' , 'T' ;
  27 , 'name' , '27' ;
  28 , 'name' , 'I' ;
  29 , 'name' , 'R' ;
  30 , 'name' , 'D' ;
  31 , 'name' , 'dD' ;
  32 , 'name' , 'C' ;
  33 , 'name' , 'N' ;
};
M_.mapping.n.eqidx = [1 3 5 7 9 11 13 15 17 19 25 33 ];
M_.mapping.c.eqidx = [1 3 5 7 9 11 13 15 17 20 25 32 ];
M_.mapping.lambda_tau.eqidx = [1 3 5 7 9 11 13 15 17 22 ];
M_.mapping.tau.eqidx = [21 25 26 ];
M_.mapping.I.eqidx = [1 3 5 7 9 11 13 15 17 21 27 28 29 30 32 33 ];
M_.mapping.T.eqidx = [26 28 ];
M_.mapping.S.eqidx = [26 27 32 33 ];
M_.mapping.R.eqidx = [29 32 33 ];
M_.mapping.D.eqidx = [30 31 ];
M_.mapping.C.eqidx = [32 ];
M_.mapping.N.eqidx = [33 ];
M_.mapping.Ui.eqidx = [22 23 25 ];
M_.mapping.Us.eqidx = [22 25 ];
M_.mapping.Ur.eqidx = [23 24 ];
M_.mapping.dD.eqidx = [31 ];
M_.mapping.c1.eqidx = [1 2 19 20 21 ];
M_.mapping.c1_dev.eqidx = [2 ];
M_.mapping.c2.eqidx = [3 4 19 20 21 ];
M_.mapping.c2_dev.eqidx = [4 ];
M_.mapping.c3.eqidx = [5 6 19 20 21 ];
M_.mapping.c3_dev.eqidx = [6 ];
M_.mapping.c4.eqidx = [7 8 19 20 21 ];
M_.mapping.c4_dev.eqidx = [8 ];
M_.mapping.c5.eqidx = [9 10 19 20 21 ];
M_.mapping.c5_dev.eqidx = [10 ];
M_.mapping.c6.eqidx = [11 12 19 20 21 ];
M_.mapping.c6_dev.eqidx = [12 ];
M_.mapping.c7.eqidx = [13 14 19 20 21 ];
M_.mapping.c7_dev.eqidx = [14 ];
M_.mapping.c8.eqidx = [15 16 19 20 21 ];
M_.mapping.c8_dev.eqidx = [16 ];
M_.mapping.c9.eqidx = [17 18 19 20 21 ];
M_.mapping.c9_dev.eqidx = [18 ];
M_.mapping.eps.eqidx = [28 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [5 6 7 8 9 ];
M_.exo_names_orig_ord = [1:1];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(33, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(26, 1);
M_.endo_trends = struct('deflator', cell(33, 1), 'log_deflator', cell(33, 1), 'growth_factor', cell(33, 1), 'log_growth_factor', cell(33, 1));
M_.NNZDerivatives = [138; -1; -1; ];
M_.static_tmp_nbr = [27; 12; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
clc;
M_.params(5) = 3;
eta = M_.params(5);
M_.params(1) = 1.82e-06;
pi_s = M_.params(1);
M_.params(2) = 0;
pi_a = M_.params(2);
M_.params(4) = 0.0007;
pi_d = M_.params(4);
M_.params(3) = 0.6993;
pi_r = M_.params(3);
M_.params(8) = 0.9992152697058329;
betta = M_.params(8);
M_.params(7) = 39.835;
A = M_.params(7);
M_.params(6) = 0.001275;
theta = M_.params(6);
M_.params(9) = 0.2;
phi1 = M_.params(9);
M_.params(10) = 0.1111111111111111;
ups1 = M_.params(10);
M_.params(11) = 0.4;
phi2 = M_.params(11);
M_.params(12) = 0.1111111111111111;
ups2 = M_.params(12);
M_.params(13) = 0.6000000000000001;
phi3 = M_.params(13);
M_.params(14) = 0.1111111111111111;
ups3 = M_.params(14);
M_.params(15) = 0.8;
phi4 = M_.params(15);
M_.params(16) = 0.1111111111111111;
ups4 = M_.params(16);
M_.params(17) = 1;
phi5 = M_.params(17);
M_.params(18) = 0.1111111111111111;
ups5 = M_.params(18);
M_.params(19) = 1.2;
phi6 = M_.params(19);
M_.params(20) = 0.1111111111111111;
ups6 = M_.params(20);
M_.params(21) = 1.4;
phi7 = M_.params(21);
M_.params(22) = 0.1111111111111111;
ups7 = M_.params(22);
M_.params(23) = 1.6;
phi8 = M_.params(23);
M_.params(24) = 0.1111111111111111;
ups8 = M_.params(24);
M_.params(25) = 1.8;
phi9 = M_.params(25);
M_.params(26) = 0.1111111111111111;
ups9 = M_.params(26);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',1,'multiplicative',0,'periods',1:1,'value',0.0001) ];
M_.exo_det_length = 0;
options_.periods = 100;
perfect_foresight_setup;
clc;
M_.params(1) = 1e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.2e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.4e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.6e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.8e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.2e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.4e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.6e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 2.8e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.2e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.4e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.6e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 3.8e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.2e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.4e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.6e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 4.8e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5.2e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5.4e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5.6e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 5.8e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 6e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 6.2e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 6.4e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 6.6e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 6.8e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7.2e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7.4e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7.6e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 7.8e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 8e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 8.20000000000001e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 8.40000000000001e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 8.60000000000001e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 8.80000000000001e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9.00000000000001e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9.20000000000001e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9.40000000000001e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9.60000000000001e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 9.80000000000001e-07;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.02e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.04e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.06e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.08e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.1e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.12e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.14e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.16e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.18e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.2e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.22e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.24e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.26e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.28e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.3e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.32e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.34e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.36e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.38e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.4e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.42e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.44e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.46e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.48e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.5e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.52e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.54e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.56e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.58e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.6e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.62e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.64e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.66e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.68e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.7e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.72e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.74e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.76e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.78e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
clc;
M_.params(1) = 1.8e-06;
pi_s = M_.params(1);
disp(['pi_s = ' num2str(pi_s)]);
options_.stack_solve_algo = 6;
perfect_foresight_solver;
PlotResults;
clean_current_folder;
save('multisector_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('multisector_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('multisector_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('multisector_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('multisector_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('multisector_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('multisector_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
