clear all; clc; close all;
addpath c:/dynare/4.6.4/matlab

% main_epimmb(  [modellist (string)], ...
%               [macrovariablelist (string)],...
%               horizon (number), re_simulate (0=no, 1=yes), ...
%               [indicator_shock_size(0=model specific, 1=common) common_shock_size])
%main_epimmb(["HHK_20","AJRT_20","ACS_21","ERT_21_NK","KUX_20"],...
main_epimmb(["HHK_20", "ACS_21","ERT_21_NK","KUX_20"],...
            ["Consumption","Labour","Output","Susceptibles","Infected","Recovered","Deaths"], ...
            100, 1, ...
            [1 0.001])
