%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'one_sector_vcu_binding';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
M_.exo_names = 'eps_l2';
M_.exo_names_tex = 'eps\_l2';
M_.exo_names_long = 'eps_l2';
M_.exo_names = char(M_.exo_names, 'eps_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_a');
M_.exo_names_long = char(M_.exo_names_long, 'eps_a');
M_.exo_names = char(M_.exo_names, 'eps_m36');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_m36');
M_.exo_names_long = char(M_.exo_names_long, 'eps_m36');
M_.exo_names = char(M_.exo_names, 'eps_n36');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_n36');
M_.exo_names_long = char(M_.exo_names_long, 'eps_n36');
M_.exo_names = char(M_.exo_names, 'eps_pop_shock36');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_pop\_shock36');
M_.exo_names_long = char(M_.exo_names_long, 'eps_pop_shock36');
M_.endo_names = 'y';
M_.endo_names_tex = 'y';
M_.endo_names_long = 'y';
M_.endo_names = char(M_.endo_names, 'ypc');
M_.endo_names_tex = char(M_.endo_names_tex, 'ypc');
M_.endo_names_long = char(M_.endo_names_long, 'ypc');
M_.endo_names = char(M_.endo_names, 'v2');
M_.endo_names_tex = char(M_.endo_names_tex, 'v2');
M_.endo_names_long = char(M_.endo_names_long, 'v2');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'cpc');
M_.endo_names_tex = char(M_.endo_names_tex, 'cpc');
M_.endo_names_long = char(M_.endo_names_long, 'cpc');
M_.endo_names = char(M_.endo_names, 'in');
M_.endo_names_tex = char(M_.endo_names_tex, 'in');
M_.endo_names_long = char(M_.endo_names_long, 'in');
M_.endo_names = char(M_.endo_names, 'inpc');
M_.endo_names_tex = char(M_.endo_names_tex, 'inpc');
M_.endo_names_long = char(M_.endo_names_long, 'inpc');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'lambdac');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdac');
M_.endo_names_long = char(M_.endo_names_long, 'lambdac');
M_.endo_names = char(M_.endo_names, 'lambdak');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdak');
M_.endo_names_long = char(M_.endo_names_long, 'lambdak');
M_.endo_names = char(M_.endo_names, 'lambdai');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdai');
M_.endo_names_long = char(M_.endo_names_long, 'lambdai');
M_.endo_names = char(M_.endo_names, 'w2');
M_.endo_names_tex = char(M_.endo_names_tex, 'w2');
M_.endo_names_long = char(M_.endo_names_long, 'w2');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'l2');
M_.endo_names_tex = char(M_.endo_names_tex, 'l2');
M_.endo_names_long = char(M_.endo_names_long, 'l2');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'pop');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop');
M_.endo_names_long = char(M_.endo_names_long, 'pop');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 'm1');
M_.endo_names_tex = char(M_.endo_names_tex, 'm1');
M_.endo_names_long = char(M_.endo_names_long, 'm1');
M_.endo_names = char(M_.endo_names, 'm2');
M_.endo_names_tex = char(M_.endo_names_tex, 'm2');
M_.endo_names_long = char(M_.endo_names_long, 'm2');
M_.endo_names = char(M_.endo_names, 'm3');
M_.endo_names_tex = char(M_.endo_names_tex, 'm3');
M_.endo_names_long = char(M_.endo_names_long, 'm3');
M_.endo_names = char(M_.endo_names, 'm4');
M_.endo_names_tex = char(M_.endo_names_tex, 'm4');
M_.endo_names_long = char(M_.endo_names_long, 'm4');
M_.endo_names = char(M_.endo_names, 'm5');
M_.endo_names_tex = char(M_.endo_names_tex, 'm5');
M_.endo_names_long = char(M_.endo_names_long, 'm5');
M_.endo_names = char(M_.endo_names, 'm6');
M_.endo_names_tex = char(M_.endo_names_tex, 'm6');
M_.endo_names_long = char(M_.endo_names_long, 'm6');
M_.endo_names = char(M_.endo_names, 'm7');
M_.endo_names_tex = char(M_.endo_names_tex, 'm7');
M_.endo_names_long = char(M_.endo_names_long, 'm7');
M_.endo_names = char(M_.endo_names, 'm8');
M_.endo_names_tex = char(M_.endo_names_tex, 'm8');
M_.endo_names_long = char(M_.endo_names_long, 'm8');
M_.endo_names = char(M_.endo_names, 'm9');
M_.endo_names_tex = char(M_.endo_names_tex, 'm9');
M_.endo_names_long = char(M_.endo_names_long, 'm9');
M_.endo_names = char(M_.endo_names, 'm10');
M_.endo_names_tex = char(M_.endo_names_tex, 'm10');
M_.endo_names_long = char(M_.endo_names_long, 'm10');
M_.endo_names = char(M_.endo_names, 'm11');
M_.endo_names_tex = char(M_.endo_names_tex, 'm11');
M_.endo_names_long = char(M_.endo_names_long, 'm11');
M_.endo_names = char(M_.endo_names, 'm12');
M_.endo_names_tex = char(M_.endo_names_tex, 'm12');
M_.endo_names_long = char(M_.endo_names_long, 'm12');
M_.endo_names = char(M_.endo_names, 'm13');
M_.endo_names_tex = char(M_.endo_names_tex, 'm13');
M_.endo_names_long = char(M_.endo_names_long, 'm13');
M_.endo_names = char(M_.endo_names, 'm14');
M_.endo_names_tex = char(M_.endo_names_tex, 'm14');
M_.endo_names_long = char(M_.endo_names_long, 'm14');
M_.endo_names = char(M_.endo_names, 'm15');
M_.endo_names_tex = char(M_.endo_names_tex, 'm15');
M_.endo_names_long = char(M_.endo_names_long, 'm15');
M_.endo_names = char(M_.endo_names, 'm16');
M_.endo_names_tex = char(M_.endo_names_tex, 'm16');
M_.endo_names_long = char(M_.endo_names_long, 'm16');
M_.endo_names = char(M_.endo_names, 'm17');
M_.endo_names_tex = char(M_.endo_names_tex, 'm17');
M_.endo_names_long = char(M_.endo_names_long, 'm17');
M_.endo_names = char(M_.endo_names, 'm18');
M_.endo_names_tex = char(M_.endo_names_tex, 'm18');
M_.endo_names_long = char(M_.endo_names_long, 'm18');
M_.endo_names = char(M_.endo_names, 'm19');
M_.endo_names_tex = char(M_.endo_names_tex, 'm19');
M_.endo_names_long = char(M_.endo_names_long, 'm19');
M_.endo_names = char(M_.endo_names, 'm20');
M_.endo_names_tex = char(M_.endo_names_tex, 'm20');
M_.endo_names_long = char(M_.endo_names_long, 'm20');
M_.endo_names = char(M_.endo_names, 'm21');
M_.endo_names_tex = char(M_.endo_names_tex, 'm21');
M_.endo_names_long = char(M_.endo_names_long, 'm21');
M_.endo_names = char(M_.endo_names, 'm22');
M_.endo_names_tex = char(M_.endo_names_tex, 'm22');
M_.endo_names_long = char(M_.endo_names_long, 'm22');
M_.endo_names = char(M_.endo_names, 'm23');
M_.endo_names_tex = char(M_.endo_names_tex, 'm23');
M_.endo_names_long = char(M_.endo_names_long, 'm23');
M_.endo_names = char(M_.endo_names, 'm24');
M_.endo_names_tex = char(M_.endo_names_tex, 'm24');
M_.endo_names_long = char(M_.endo_names_long, 'm24');
M_.endo_names = char(M_.endo_names, 'm25');
M_.endo_names_tex = char(M_.endo_names_tex, 'm25');
M_.endo_names_long = char(M_.endo_names_long, 'm25');
M_.endo_names = char(M_.endo_names, 'm26');
M_.endo_names_tex = char(M_.endo_names_tex, 'm26');
M_.endo_names_long = char(M_.endo_names_long, 'm26');
M_.endo_names = char(M_.endo_names, 'm27');
M_.endo_names_tex = char(M_.endo_names_tex, 'm27');
M_.endo_names_long = char(M_.endo_names_long, 'm27');
M_.endo_names = char(M_.endo_names, 'm28');
M_.endo_names_tex = char(M_.endo_names_tex, 'm28');
M_.endo_names_long = char(M_.endo_names_long, 'm28');
M_.endo_names = char(M_.endo_names, 'm29');
M_.endo_names_tex = char(M_.endo_names_tex, 'm29');
M_.endo_names_long = char(M_.endo_names_long, 'm29');
M_.endo_names = char(M_.endo_names, 'm30');
M_.endo_names_tex = char(M_.endo_names_tex, 'm30');
M_.endo_names_long = char(M_.endo_names_long, 'm30');
M_.endo_names = char(M_.endo_names, 'm31');
M_.endo_names_tex = char(M_.endo_names_tex, 'm31');
M_.endo_names_long = char(M_.endo_names_long, 'm31');
M_.endo_names = char(M_.endo_names, 'm32');
M_.endo_names_tex = char(M_.endo_names_tex, 'm32');
M_.endo_names_long = char(M_.endo_names_long, 'm32');
M_.endo_names = char(M_.endo_names, 'm33');
M_.endo_names_tex = char(M_.endo_names_tex, 'm33');
M_.endo_names_long = char(M_.endo_names_long, 'm33');
M_.endo_names = char(M_.endo_names, 'm34');
M_.endo_names_tex = char(M_.endo_names_tex, 'm34');
M_.endo_names_long = char(M_.endo_names_long, 'm34');
M_.endo_names = char(M_.endo_names, 'm35');
M_.endo_names_tex = char(M_.endo_names_tex, 'm35');
M_.endo_names_long = char(M_.endo_names_long, 'm35');
M_.endo_names = char(M_.endo_names, 'm36');
M_.endo_names_tex = char(M_.endo_names_tex, 'm36');
M_.endo_names_long = char(M_.endo_names_long, 'm36');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'n1');
M_.endo_names_tex = char(M_.endo_names_tex, 'n1');
M_.endo_names_long = char(M_.endo_names_long, 'n1');
M_.endo_names = char(M_.endo_names, 'n2');
M_.endo_names_tex = char(M_.endo_names_tex, 'n2');
M_.endo_names_long = char(M_.endo_names_long, 'n2');
M_.endo_names = char(M_.endo_names, 'n3');
M_.endo_names_tex = char(M_.endo_names_tex, 'n3');
M_.endo_names_long = char(M_.endo_names_long, 'n3');
M_.endo_names = char(M_.endo_names, 'n4');
M_.endo_names_tex = char(M_.endo_names_tex, 'n4');
M_.endo_names_long = char(M_.endo_names_long, 'n4');
M_.endo_names = char(M_.endo_names, 'n5');
M_.endo_names_tex = char(M_.endo_names_tex, 'n5');
M_.endo_names_long = char(M_.endo_names_long, 'n5');
M_.endo_names = char(M_.endo_names, 'n6');
M_.endo_names_tex = char(M_.endo_names_tex, 'n6');
M_.endo_names_long = char(M_.endo_names_long, 'n6');
M_.endo_names = char(M_.endo_names, 'n7');
M_.endo_names_tex = char(M_.endo_names_tex, 'n7');
M_.endo_names_long = char(M_.endo_names_long, 'n7');
M_.endo_names = char(M_.endo_names, 'n8');
M_.endo_names_tex = char(M_.endo_names_tex, 'n8');
M_.endo_names_long = char(M_.endo_names_long, 'n8');
M_.endo_names = char(M_.endo_names, 'n9');
M_.endo_names_tex = char(M_.endo_names_tex, 'n9');
M_.endo_names_long = char(M_.endo_names_long, 'n9');
M_.endo_names = char(M_.endo_names, 'n10');
M_.endo_names_tex = char(M_.endo_names_tex, 'n10');
M_.endo_names_long = char(M_.endo_names_long, 'n10');
M_.endo_names = char(M_.endo_names, 'n11');
M_.endo_names_tex = char(M_.endo_names_tex, 'n11');
M_.endo_names_long = char(M_.endo_names_long, 'n11');
M_.endo_names = char(M_.endo_names, 'n12');
M_.endo_names_tex = char(M_.endo_names_tex, 'n12');
M_.endo_names_long = char(M_.endo_names_long, 'n12');
M_.endo_names = char(M_.endo_names, 'n13');
M_.endo_names_tex = char(M_.endo_names_tex, 'n13');
M_.endo_names_long = char(M_.endo_names_long, 'n13');
M_.endo_names = char(M_.endo_names, 'n14');
M_.endo_names_tex = char(M_.endo_names_tex, 'n14');
M_.endo_names_long = char(M_.endo_names_long, 'n14');
M_.endo_names = char(M_.endo_names, 'n15');
M_.endo_names_tex = char(M_.endo_names_tex, 'n15');
M_.endo_names_long = char(M_.endo_names_long, 'n15');
M_.endo_names = char(M_.endo_names, 'n16');
M_.endo_names_tex = char(M_.endo_names_tex, 'n16');
M_.endo_names_long = char(M_.endo_names_long, 'n16');
M_.endo_names = char(M_.endo_names, 'n17');
M_.endo_names_tex = char(M_.endo_names_tex, 'n17');
M_.endo_names_long = char(M_.endo_names_long, 'n17');
M_.endo_names = char(M_.endo_names, 'n18');
M_.endo_names_tex = char(M_.endo_names_tex, 'n18');
M_.endo_names_long = char(M_.endo_names_long, 'n18');
M_.endo_names = char(M_.endo_names, 'n19');
M_.endo_names_tex = char(M_.endo_names_tex, 'n19');
M_.endo_names_long = char(M_.endo_names_long, 'n19');
M_.endo_names = char(M_.endo_names, 'n20');
M_.endo_names_tex = char(M_.endo_names_tex, 'n20');
M_.endo_names_long = char(M_.endo_names_long, 'n20');
M_.endo_names = char(M_.endo_names, 'n21');
M_.endo_names_tex = char(M_.endo_names_tex, 'n21');
M_.endo_names_long = char(M_.endo_names_long, 'n21');
M_.endo_names = char(M_.endo_names, 'n22');
M_.endo_names_tex = char(M_.endo_names_tex, 'n22');
M_.endo_names_long = char(M_.endo_names_long, 'n22');
M_.endo_names = char(M_.endo_names, 'n23');
M_.endo_names_tex = char(M_.endo_names_tex, 'n23');
M_.endo_names_long = char(M_.endo_names_long, 'n23');
M_.endo_names = char(M_.endo_names, 'n24');
M_.endo_names_tex = char(M_.endo_names_tex, 'n24');
M_.endo_names_long = char(M_.endo_names_long, 'n24');
M_.endo_names = char(M_.endo_names, 'n25');
M_.endo_names_tex = char(M_.endo_names_tex, 'n25');
M_.endo_names_long = char(M_.endo_names_long, 'n25');
M_.endo_names = char(M_.endo_names, 'n26');
M_.endo_names_tex = char(M_.endo_names_tex, 'n26');
M_.endo_names_long = char(M_.endo_names_long, 'n26');
M_.endo_names = char(M_.endo_names, 'n27');
M_.endo_names_tex = char(M_.endo_names_tex, 'n27');
M_.endo_names_long = char(M_.endo_names_long, 'n27');
M_.endo_names = char(M_.endo_names, 'n28');
M_.endo_names_tex = char(M_.endo_names_tex, 'n28');
M_.endo_names_long = char(M_.endo_names_long, 'n28');
M_.endo_names = char(M_.endo_names, 'n29');
M_.endo_names_tex = char(M_.endo_names_tex, 'n29');
M_.endo_names_long = char(M_.endo_names_long, 'n29');
M_.endo_names = char(M_.endo_names, 'n30');
M_.endo_names_tex = char(M_.endo_names_tex, 'n30');
M_.endo_names_long = char(M_.endo_names_long, 'n30');
M_.endo_names = char(M_.endo_names, 'n31');
M_.endo_names_tex = char(M_.endo_names_tex, 'n31');
M_.endo_names_long = char(M_.endo_names_long, 'n31');
M_.endo_names = char(M_.endo_names, 'n32');
M_.endo_names_tex = char(M_.endo_names_tex, 'n32');
M_.endo_names_long = char(M_.endo_names_long, 'n32');
M_.endo_names = char(M_.endo_names, 'n33');
M_.endo_names_tex = char(M_.endo_names_tex, 'n33');
M_.endo_names_long = char(M_.endo_names_long, 'n33');
M_.endo_names = char(M_.endo_names, 'n34');
M_.endo_names_tex = char(M_.endo_names_tex, 'n34');
M_.endo_names_long = char(M_.endo_names_long, 'n34');
M_.endo_names = char(M_.endo_names, 'n35');
M_.endo_names_tex = char(M_.endo_names_tex, 'n35');
M_.endo_names_long = char(M_.endo_names_long, 'n35');
M_.endo_names = char(M_.endo_names, 'n36');
M_.endo_names_tex = char(M_.endo_names_tex, 'n36');
M_.endo_names_long = char(M_.endo_names_long, 'n36');
M_.endo_names = char(M_.endo_names, 'pop_shock');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock');
M_.endo_names = char(M_.endo_names, 'pop_shock1');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock1');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock1');
M_.endo_names = char(M_.endo_names, 'pop_shock2');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock2');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock2');
M_.endo_names = char(M_.endo_names, 'pop_shock3');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock3');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock3');
M_.endo_names = char(M_.endo_names, 'pop_shock4');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock4');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock4');
M_.endo_names = char(M_.endo_names, 'pop_shock5');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock5');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock5');
M_.endo_names = char(M_.endo_names, 'pop_shock6');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock6');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock6');
M_.endo_names = char(M_.endo_names, 'pop_shock7');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock7');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock7');
M_.endo_names = char(M_.endo_names, 'pop_shock8');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock8');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock8');
M_.endo_names = char(M_.endo_names, 'pop_shock9');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock9');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock9');
M_.endo_names = char(M_.endo_names, 'pop_shock10');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock10');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock10');
M_.endo_names = char(M_.endo_names, 'pop_shock11');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock11');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock11');
M_.endo_names = char(M_.endo_names, 'pop_shock12');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock12');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock12');
M_.endo_names = char(M_.endo_names, 'pop_shock13');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock13');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock13');
M_.endo_names = char(M_.endo_names, 'pop_shock14');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock14');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock14');
M_.endo_names = char(M_.endo_names, 'pop_shock15');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock15');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock15');
M_.endo_names = char(M_.endo_names, 'pop_shock16');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock16');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock16');
M_.endo_names = char(M_.endo_names, 'pop_shock17');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock17');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock17');
M_.endo_names = char(M_.endo_names, 'pop_shock18');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock18');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock18');
M_.endo_names = char(M_.endo_names, 'pop_shock19');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock19');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock19');
M_.endo_names = char(M_.endo_names, 'pop_shock20');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock20');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock20');
M_.endo_names = char(M_.endo_names, 'pop_shock21');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock21');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock21');
M_.endo_names = char(M_.endo_names, 'pop_shock22');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock22');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock22');
M_.endo_names = char(M_.endo_names, 'pop_shock23');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock23');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock23');
M_.endo_names = char(M_.endo_names, 'pop_shock24');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock24');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock24');
M_.endo_names = char(M_.endo_names, 'pop_shock25');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock25');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock25');
M_.endo_names = char(M_.endo_names, 'pop_shock26');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock26');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock26');
M_.endo_names = char(M_.endo_names, 'pop_shock27');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock27');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock27');
M_.endo_names = char(M_.endo_names, 'pop_shock28');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock28');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock28');
M_.endo_names = char(M_.endo_names, 'pop_shock29');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock29');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock29');
M_.endo_names = char(M_.endo_names, 'pop_shock30');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock30');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock30');
M_.endo_names = char(M_.endo_names, 'pop_shock31');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock31');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock31');
M_.endo_names = char(M_.endo_names, 'pop_shock32');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock32');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock32');
M_.endo_names = char(M_.endo_names, 'pop_shock33');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock33');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock33');
M_.endo_names = char(M_.endo_names, 'pop_shock34');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock34');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock34');
M_.endo_names = char(M_.endo_names, 'pop_shock35');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock35');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock35');
M_.endo_names = char(M_.endo_names, 'pop_shock36');
M_.endo_names_tex = char(M_.endo_names_tex, 'pop\_shock36');
M_.endo_names_long = char(M_.endo_names_long, 'pop_shock36');
M_.endo_partitions = struct();
M_.param_names = 'alphap';
M_.param_names_tex = 'alphap';
M_.param_names_long = 'alphap';
M_.param_names = char(M_.param_names, 'kappap');
M_.param_names_tex = char(M_.param_names_tex, 'kappap');
M_.param_names_long = char(M_.param_names_long, 'kappap');
M_.param_names = char(M_.param_names, 'rhop');
M_.param_names_tex = char(M_.param_names_tex, 'rhop');
M_.param_names_long = char(M_.param_names_long, 'rhop');
M_.param_names = char(M_.param_names, 'rhop_l');
M_.param_names_tex = char(M_.param_names_tex, 'rhop\_l');
M_.param_names_long = char(M_.param_names_long, 'rhop_l');
M_.param_names = char(M_.param_names, 'rhop_a');
M_.param_names_tex = char(M_.param_names_tex, 'rhop\_a');
M_.param_names_long = char(M_.param_names_long, 'rhop_a');
M_.param_names = char(M_.param_names, 'betap');
M_.param_names_tex = char(M_.param_names_tex, 'betap');
M_.param_names_long = char(M_.param_names_long, 'betap');
M_.param_names = char(M_.param_names, 'zetap');
M_.param_names_tex = char(M_.param_names_tex, 'zetap');
M_.param_names_long = char(M_.param_names_long, 'zetap');
M_.param_names = char(M_.param_names, 'deltap');
M_.param_names_tex = char(M_.param_names_tex, 'deltap');
M_.param_names_long = char(M_.param_names_long, 'deltap');
M_.param_names = char(M_.param_names, 'nup');
M_.param_names_tex = char(M_.param_names_tex, 'nup');
M_.param_names_long = char(M_.param_names_long, 'nup');
M_.param_names = char(M_.param_names, 'nu0p');
M_.param_names_tex = char(M_.param_names_tex, 'nu0p');
M_.param_names_long = char(M_.param_names_long, 'nu0p');
M_.param_names = char(M_.param_names, 'in_ss');
M_.param_names_tex = char(M_.param_names_tex, 'in\_ss');
M_.param_names_long = char(M_.param_names_long, 'in_ss');
M_.param_names = char(M_.param_names, 'l2_ss');
M_.param_names_tex = char(M_.param_names_tex, 'l2\_ss');
M_.param_names_long = char(M_.param_names_long, 'l2_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 128;
M_.param_nbr = 12;
M_.orig_endo_nbr = 128;
M_.aux_vars = [];
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('one_sector_vcu_binding_static');
erase_compiled_function('one_sector_vcu_binding_dynamic');
M_.orig_eq_nbr = 128;
M_.eq_nbr = 128;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 115 0;
 0 116 0;
 0 117 0;
 0 118 0;
 1 119 243;
 2 120 244;
 0 121 0;
 3 122 0;
 0 123 245;
 0 124 246;
 0 125 0;
 0 126 0;
 0 127 247;
 4 128 0;
 5 129 0;
 0 130 248;
 6 131 249;
 0 132 0;
 7 133 0;
 8 134 0;
 9 135 0;
 10 136 0;
 11 137 0;
 12 138 0;
 13 139 0;
 14 140 0;
 15 141 0;
 16 142 0;
 17 143 0;
 18 144 0;
 19 145 0;
 20 146 0;
 21 147 0;
 22 148 0;
 23 149 0;
 24 150 0;
 25 151 0;
 26 152 0;
 27 153 0;
 28 154 0;
 29 155 0;
 30 156 0;
 31 157 0;
 32 158 0;
 33 159 0;
 34 160 0;
 35 161 0;
 36 162 0;
 37 163 0;
 38 164 0;
 39 165 0;
 40 166 0;
 41 167 0;
 42 168 0;
 0 169 0;
 43 170 0;
 44 171 0;
 45 172 0;
 46 173 0;
 47 174 0;
 48 175 0;
 49 176 0;
 50 177 0;
 51 178 0;
 52 179 0;
 53 180 0;
 54 181 0;
 55 182 0;
 56 183 0;
 57 184 0;
 58 185 0;
 59 186 0;
 60 187 0;
 61 188 0;
 62 189 0;
 63 190 0;
 64 191 0;
 65 192 0;
 66 193 0;
 67 194 0;
 68 195 0;
 69 196 0;
 70 197 0;
 71 198 0;
 72 199 0;
 73 200 0;
 74 201 0;
 75 202 0;
 76 203 0;
 77 204 0;
 78 205 0;
 0 206 0;
 79 207 0;
 80 208 0;
 81 209 0;
 82 210 0;
 83 211 0;
 84 212 0;
 85 213 0;
 86 214 0;
 87 215 0;
 88 216 0;
 89 217 0;
 90 218 0;
 91 219 0;
 92 220 0;
 93 221 0;
 94 222 0;
 95 223 0;
 96 224 0;
 97 225 0;
 98 226 0;
 99 227 0;
 100 228 0;
 101 229 0;
 102 230 0;
 103 231 0;
 104 232 0;
 105 233 0;
 106 234 0;
 107 235 0;
 108 236 0;
 109 237 0;
 110 238 0;
 111 239 0;
 112 240 0;
 113 241 0;
 114 242 0;]';
M_.nstatic = 10;
M_.nfwrd   = 4;
M_.npred   = 111;
M_.nboth   = 3;
M_.nsfwrd   = 7;
M_.nspred   = 114;
M_.ndynamic   = 118;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(128, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(12, 1);
M_.NNZDerivatives = [284; 78; -1];
save('one_sector_vcu_binding_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('one_sector_vcu_binding_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('one_sector_vcu_binding_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('one_sector_vcu_binding_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('one_sector_vcu_binding_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('one_sector_vcu_binding_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('one_sector_vcu_binding_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
