name: Calculate OCP data
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: 'Calculate OCP data'
  cancel-in-progress: true
jobs:
  list-models:
    outputs:
      models: ${{ steps.list-models.outputs.models }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - id: list-models
        # thanks, https://code.dblock.org/2021/09/03/generating-task-matrix-by-looping-over-repo-files-with-github-actions.html
        run: echo "::set-output name=models::$(ls -l models | awk '/^d/ {print $9}' | jq -R -s -c 'split("\n")[:-1]')"
        
  simulate:
    needs: 
      - list-models
      
    name: Run Simulation
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # linter yells "invalid type", but the parsed json will fit in here just fine
        MODEL_NAME: ${{ fromJson(needs.list-models.outputs.models) }}
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
    
      - uses: actions/cache@v3
        id: cache-results
        with:
          path: results/*.json
          key: ${{ hashFiles(format('models/{0}/**/*', matrix.MODEL_NAME)) }}
    
      - if: steps.cache-results.outputs.cache-hit != 'true'
        name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        
      - if: steps.cache-results.outputs.cache-hit != 'true'
        name: Set up Dynare
        run: "DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-upgrade --no-install-recommends -y dynare dynare-matlab x13as"
        
      - if: steps.cache-results.outputs.cache-hit != 'true'
        name: Run script
        uses: matlab-actions/run-command@v1
        env:
          MODEL_NAME: ${{ matrix.MODEL_NAME }}
          LD_PRELOAD: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
        with:
          command: ci
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results/*.json

  upload:
      name: Upload
      needs: simulate
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: results
            path: results
        - name: List result files
          run: "ls -l results"
       
