name: Calculate OCP data
on:
  push:
    branches:
      - main
concurrency:
  group: 'Calculate OCP data'
  cancel-in-progress: true
jobs:
  simulate:
    name: Run Simulation
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        MODEL_NAME:
          - A_20
          #- AAL_20
          #- ACS_21
          #- AJRT_20
          #- ALS_20
          #- BCG_21
          #- BKST_21
          #- CDL_21
          #- CF_20
          #- ERT_21
          #- ERT_21_Ineq
          #- ERT_21_NK
          #- ERT_21_Test
          #- GP_20
          #- HKK_20
          #- JPV_21
         # - KUX_20
         # - LFA_22
         # - MY_21
         # - R_20
          #- V_20
          #- VDS_21
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run:  echo "${{ format('models/{0}/**/*', matrix.MODEL_NAME) }}"; echo "${{ hashFiles(format('models/{0}/**/*', matrix.MODEL_NAME)) }}"
      - uses: actions/cache@v3
        id: cache-results
        with:
          path: results/*.json
          key: ${{ hashFiles(format('models/{0}/**/*', matrix.MODEL_NAME)) }}
      - run: echo "${{steps.cache.outputs.cache-hit}}"  
      - if: steps.cache-results.outputs.cache-hit != 'true'
        name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        
      - if: steps.cache-results.outputs.cache-hit != 'true'
        name: Set up Dynare
        run: "DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-upgrade --no-install-recommends -y dynare dynare-matlab x13as"
        
      - if: steps.cache-results.outputs.cache-hit != 'true'
        name: Run script
        uses: matlab-actions/run-command@v1
        env:
          MODEL_NAME: ${{ matrix.MODEL_NAME }}
          LD_PRELOAD: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
        with:
          command: ci
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results/*.json

  upload:
      name: Upload
      needs: simulate
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: results
            path: results
        - name: List result files
          run: "ls -l results"
       
